### ISSUE TITLE
Publish the source code

### ISSUE THREAD

**Issue by DavidLibeau** [HearthstoneAccess/HearthstoneAccess#1]
You wrote "the code is open source" here: https://github.com/HearthstoneAccess/hearthstoneaccess.github.io/blob/master/index.html#L92. However, this repo contains only a zip file with compressed libraries (`dll` files) and not the source code.

Is it possible to have the source code? Also, can you add a license?

Thanks in advance.

**Comment by sebastientromp** [comment]
I would very much like to have a way to compile everything from the sources as well. It would also make contributing easier.

**Comment by GuideDev** [comment]
Hello.

The source code for the patch used to generate those libraries is all in the diff.patch file.

Keep in mind this is a patch and not a standalone project. It's also not something you can compile on its own as Hearthstone itself is not open source.

Contributing is certainly possible but not easy by any means. I really appreciate everyone who's offered to contribute but I'm afraid doing so won't be easy.

**Comment by sebastientromp** [comment]
Thanks for your reply! I already am working with the decompiled libraries myself to extract infos, so this particular bit is not an issue, but I don't recompile them back. I'll try to find a way to do it, then I'll come back here :)

Cheers!

**Comment by ogomez92** [comment]
so, just curious, are you working closely with Blizzard entertainment to
make this possible? Or are you working on your own? Have the Blizzard guys
shown any interest at all?

**Comment by GuideDev** [comment]
@sebastientromp if you manage to set something up to work on the patch itself feel free to open a MR with your diff and I'll have a look :) Don't worry about compiling anything or publishing assemblies. All I need is the diff.

@ogomez92 I'm not affiliated with Blizzard. I'm working on my own.

**Comment by DavidLibeau** [comment]
I didn't understood the answer. HearthstoneAccess is a mod. So even if Hearthstone is not open source, you can publish the source code. That's exactly this situation for this mod of Minecraft: https://framagit.org/DavidLibeau/gametospeech-minecraft.

In the `diff.patch` it is mentionned the `AccessibleCard.cs` : where is this file? Can we have the source code?

I am doing a PhD about audio description in games (see https://gametospeech.com) and if I want to study your work, I cannot do it without source code…

**Comment by GuideDev** [comment]
@DavidLibeau That file is exactly where you read the `AccessibleCard.cs`. So lines 1168 to 1509. Have a look at how `git diff` works if you're still confused about what any of that means.

I had a look at your 2 minutes video and I'm not sure you need to dig into the code to achieve any of your PhD though. I'm also not sure having a gameToSpeech API would be practical unless you give up on the livestreaming part of it. Not to mention this would increase game development costs significantly which would be a major turndown for studios.

Here's my very off the top of my head view on how you could approach what you're trying to do in a practical manner:
1. Get game studios to implement accessibility in their games using a well known screen-reader API. Tolk is a perfect example of this on Windows, but an additional abstraction library covering Mac and Linux would be the end goal.
2. Make the screen-reader API either output text via the screen-reader if the player is using a screen-reader or output text over your GameToSpeech API - which would now become a simple text forwarding API.
3. Sync the audio coming from the livestreaming service in your diagram with the text you receive over the text forwarding API. You could approach this in a generic manner by having a real-time clock in your speech API and tying timestamps to both audio frames and TTS outputs.

If you wanted to set a proof of concept using Hearthstone Access, here's how you could approach it:
1. Build that text forwarding API
2. Extend Tolk to be able to output over the text forwarding API, registering timestamps for both TTS and audio
3. Build the client for the text forwarding API to be used by the spectator
4. Have the client sync the speech with the audio coming from the livestream API

If you want to simplify it even further, you could even drop the automatic audio sync at the beginning and simply allow the spectator to sync the TTS with the game audio. This would be similar to people synchronizing subtitles with movie files. Using Hearthstone as an example, it would be quite easy for someone to use the "Your turn" audio and speech to synchronize things manually for example. You would naturally need to handle edge cases such as the livestream breaking but all of it should be approachable.

Best of luck with your PhD by the way. It would be really cool to see something come out of it.

**Comment by DavidLibeau** [comment]
Thanks for your "off the top of your head view" and comments on my PhD, but that really not what I asked for. Not at all. Especially if you only saw a 2 minutes video of it. Telling me what should I do or not with my PhD without showing any experience or citing any reference is simply disrespectful.

What I asked for, is the source code of Hearthstone Access. The `git diff` log is not source code even if it do contains code. You are now on GitHub which is a platform that handle collaboration through `git` already. How the repo is right now do not permit users to contribute. Open source is about publishing all the source code following these guidelines : https://opensource.org/osd. I also asked for a license. Can you tell us what is the license of Hearthstone Access?

**Comment by GuideDev** [comment]
@DavidLibeau My apologies if I sounded disrespectful, but I wasn't trying to tell you what to do or not to do with your PhD. I was merely trying to provide you a first step so you could try to get something up and running and hopefully make everything clearer for you.

I'll repeat this one last time: The source code for Hearthstone Access is all in the `git diff` log. The source code for Hearthstone Access however cannot be compiled as is given that **it is a patch and not a self-containined project.** Hearthstone is not open source and I sure am not going to distribute decompiled versions of it myself.

If it helps, you can think about this entire repo as property of Blizzard Entertainment. And you can think of GuideDev as someone who doesn't work or represent Blizzard but is helping the blind community enjoy their game. The patch itself is open source for transparency and will be put down if Blizzard wants to use it to implement things natively. The assemblies are also versioned in case someone from Blizzard's security team for example has the chance to inspect them to confirm no malicious code is being distributed.

Do note however that technically proficient people will be able to build and play the game without ever touching the assemblies published in this repo. The assemblies merely exist because few people would be able to understand how to build it and the purpose is to enable all blind gamers to play the game and not just the most technically proficient ones.

I'm done with this discussion. I'm merely trying to help and quite frankly have no interest in arguing over the Internet.

Best of luck with your PhD.

**Comment by zersiax** [comment]
@DavidLibeau HearthstoneAccess is not so much a mod as it is a patch, that is, it patches new code into the already existing executable. That code is, in fact, up on Github, in the diff, as @GuideDev already states.

The mod you link to here works differently; there is a support architecture in place to give mod authors a way to mod the game without having to touch the executable itself, so Minecraft, Slay the Spire etc. mods are essentially just self-contained programs that talk to the target game, whereas this is more of a "do the game like you normally do, except on line X of file Y, add lines Z". Hearthstone wasn't made to be modded in this manner and, praise where credit is due, what @GuideDev  is doing here is pretty next-level :)
Honestly I WOULD contribute, but I know very little about decompiling c#-based code and writing patches so while I'm looking at the diff, it's mostly so I can give more targeted feedback because I know what parts of the added code are doing :)

**Comment by DavidLibeau** [comment]
@zersiax For Minecraft, and the mod I linked ahead, it is not a self-contained program. It's a piece of code in Minecraft. And, as you can see, you don't have Minecraft code because the `.gitignore` file is excluding Minecraft code.

And if what you are saying is right, then the `diff.patch` file contains copyrighted code from Blizzard: that would be all the lines not in green (here it seems to only have one like that: https://github.com/HearthstoneAccess/HearthstoneAccess/blob/master/diff.patch#L9). Then, I don't see why we don't have the code into separate files.

I would not contribute as the code do not have any license attached.
