### ISSUE TITLE
Investigate summoning minion issue reported by 2 players

### ISSUE THREAD

**Issue by GuideDev** [HearthstoneAccess/HearthstoneAccess#13]
2 players have reported the same issue and it seemed to go away by exiting fullscreen mode. Something to do with resolutions and their particular set up probably but haven't been able to reproduce yet. Waiting for videos or screenshots.

See https://forum.audiogames.net/post/658462/#p658462

**Comment by GuideDev** [comment]
A third player ran into this and provided a video. The problem is on the client side and not the game. Updated the documentation with information if anyone runs into this.

**Comment by zersiax** [comment]
I have some more insight on this. The reason cited above doesn't seem to be the only reason this happens.
I was on the fringes of witnessing someone troubleshooting this on a headless machine with a HDMI dummy plug emulating a screen in order to trick the GPU into coming on rather than staying off, some mac models require this even when running Windows.
For this person, the problem was that their display was in portrait orientation, rather than landscape. The game really doesn't like this; trying to toggle full screen does absolutely nothing and it took a while to figure out this was the culprit.
Hope that helps :)

**Comment by GuideDev** [comment]
Thanks @zersiax! I actually asked if someone was running headless at some point but none of the reporters were so I never got around to testing it :) The mac one is a really nice find too, thanks for testing it out!

The game really doesn't like portrait-like resolutions. It actually tries to enforce landscape resolutions and aspect ratios when you resize the window manually but it doesn't always work. I've added the in-game resolutions dropdown to the mod so people will be able to use it once I release the next version. Hopefully that'll make it so people can at least choose a very small landscape resolution that still fits in portrait mode.

Anyways, I'll add your findings to the help section as well as it might help someone. Thanks again.
