### ISSUE TITLE
Make "e" end the Mulligan Phase

### ISSUE THREAD

**Issue by BlindGuyNW** [HearthstoneAccess/HearthstoneAccess#17]
Issue: Currently, the mulligan phase ends when the space-baar is pressed, but space-bar isn't used for end turn anywhere else.
Suggested fix: Make "e," also end the mulligan phase, or add spacebar as an alternative in all other situations where ending a turn is required.

**Comment by ThiagoBzn** [comment]
na, that's fine. the mod has normal keys, which makes it cooler. I
think that as it is configured it is fine.

2021-08-11 0:32 GMT-03:00, Zachary Kline ***@***.***>:

**Comment by Timtam** [comment]
I think the space bar for continuing is very unintuitive as well, but because the usual PC navigation scheme uses the space bar for checking/unchecking things and enter to submit. Thats why i'd suggest to turn things around in the mulligan phase, enter submits and the space bar checks/unchecks the cards to shuffle back, + switching between the cards should tell you if a card is currently checked or not (if possible). I would not opt to go with the e key however, e should be reserved for ending the turn only.

**Comment by aefren** [comment]
Agree with the Space Bar to check or uncheck.

**Comment by GuideDev** [comment]
Thanks for the feedback everyone. Agree with space to check. This has just been released in the new version.
